language: csharp
mono: none
dotnet: 2.1.200
install:
    - apt install dotnet-dev-1.1.9 -y
script:
    - dotnet --info
    - dotnet clean
    - dotnet build --configuration Release
    - dotnet test Minicloner.Tests/Minicloner.Tests.csproj --configuration Release --no-build