language: csharp
mono: none
dotnet: 1.1.5
script:
    - dotnet --info
    - dotnet clean
    - dotnet build --configuration Release
    - dotnet test Minicloner.Tests/Minicloner.Tests.csproj --configuration Release --no-build