steps:
- script: dotnet build --configuration Release
  displayName: Build
  failOnStderr: true
- script: dotnet test Minicloner.Tests/Minicloner.Tests.csproj --configuration Release --logger "trx;" --no-build
  displayName: Test
  failOnStderr: true