steps:
- task: DotNetCoreInstaller@0
  displayName: Install dotnet SDK
  inputs:
    packageType: sdk
    version: 2.1.300
- script: dotnet --info
  displayName: dotnet info
  failOnStderr: true
- script: dotnet build --configuration Release
  displayName: Build
  failOnStderr: true
- script: dotnet test Minicloner.Tests/Minicloner.Tests.csproj --configuration Release --logger "trx;" --no-build
  displayName: Test
  failOnStderr: true