jobs:
- job: Windows
  pool:
    vmImage: windows-2019
  steps:
  - template: build-steps.yml
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: build-steps.yml
- job: macOS
  pool:
    vmImage: macOS-10.14
  steps:
  - template: build-steps.yml