jobs:
- job: Build
  
  strategy:
    matrix:
      Windows:
        imageName: 'windows-2019'
        os: 'Windows'
      Linux:
        imageName: 'ubuntu-16.04'
        os: 'Linux'
      macOS:
        imageName: 'macOS-10.14'
        os: 'macOS'

  pool:
    vmImage: $(imageName)

  steps:
  - task: UseDotNet@2
    displayName: 'Install dotnet SDK 2.2.203'
    inputs:
      version: '2.2.203'

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      arguments: '--configuration Release'

  - task: DotNetCoreCLI@2
    displayName: 'Test .NET Core 2.0'
    inputs:
      command: 'test'
      projects: 'Minicloner.Tests/Minicloner.Tests.csproj'
      arguments: '--configuration Release --framework netcoreapp2.0 --logger "trx;LogFileName=NetCore2.0-$(os).trx" --no-build'
      publishTestResults: false

  - task: PublishTestResults@2
    displayName: 'Publish Test Results .NET Core 2.0'
    inputs:
      testRunner: 'VSTest'
      testResultsFiles: '**/NetCore2.0-$(os)*.trx'
      testRunTitle: '.NET Core 2.0 - $(os)'
      failTaskOnFailedTests: true

  - task: UseDotNet@2
    displayName: 'Install dotnet SDK 1.1.12'
    inputs:
      version: '1.1.12'

  - task: DotNetCoreCLI@1
    displayName: 'Test .NET Core 1.0'
    inputs:
      command: 'test'
      projects: 'Minicloner.Tests/Minicloner.Tests.csproj'
      arguments: '--configuration Release --framework netcoreapp1.0 --logger "trx;LogFileName=NetCore1.0-  $(os).trx" --no-build'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results .NET Core 1.0'
    inputs:
      testRunner: 'VSTest'
      testResultsFiles: '**/NetCore1.0-$(os)*.trx'
      testRunTitle: '.NET Core 1.0 - $(os)'
      failTaskOnFailedTests: true