jobs:
- job: Windows
  pool:
    vmImage: windows-2019
    steps:
    - task: UseDotNet@2
      displayName: Install dotnet SDK
      inputs:
        version: 2.2.203
    - task: DotNetCoreCLI@2
      displayName: SDK Info
      inputs:
        command: custom
        custom: --info
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        arguments: --configuration Release
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: Minicloner.Tests/Minicloner.Tests.csproj
        arguments: --configuration Release
        publishTestResults: true
        nobuild: true
- job: Linux
  pool:
    vmImage: ubuntu-16.04
    steps:
    - task: UseDotNet@2
      displayName: Install dotnet SDK
      inputs:
        version: 2.2.203
    - task: DotNetCoreCLI@2
      displayName: SDK Info
      inputs:
        command: custom
        custom: --info
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        arguments: --configuration Release
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: Minicloner.Tests/Minicloner.Tests.csproj
        arguments: --configuration Release
        publishTestResults: true
        nobuild: true
- job: macOS
  pool:
    vmImage: macOS-10.14
    steps:
    - task: UseDotNet@2
      displayName: Install dotnet SDK
      inputs:
        version: 2.2.203
    - task: DotNetCoreCLI@2
      displayName: SDK Info
      inputs:
        command: custom
        custom: --info
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        arguments: --configuration Release
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: Minicloner.Tests/Minicloner.Tests.csproj
        arguments: --configuration Release
        publishTestResults: true
        nobuild: true