name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019, ubuntu-20.04, macOS-11]

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET SDKs
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          1.1.14
          2.2.207
          3.1.426
          5.0.408

    - name: dotnet info
      run: dotnet --info

    - name: Install dotnet-outdated
      run: dotnet tool update --global dotnet-outdated-tool --version 4.5.0

    - name: Clear Nuget cache
      run: dotnet nuget locals all --clear

    - name: Restore
      run: dotnet restore

    - name: Run dotnet-outdated
      run: dotnet outdated #--fail-on-updates

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build